name: Build CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'demo/**'
    - 'README.md'
    - 'LICENSE'
    - '.gitignore'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build
      env:
        GRADLE_VERSION: 7.0.2
      run: |
        gradle wrapper --gradle-version $GRADLE_VERSION
        ./gradlew :retoast:publish demo:assembleDebug

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ReToast-products
        path: |
          local-mvn-repo
          retoast/build/outputs/mapping/release
          demo/build/outputs/apk/debug/demo-debug.apk